import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.css'
import { VisualEditing, groq } from 'next-sanity'
import Link from 'next/link'
import { sanitize } from '@/util/src/sanitize'
import { sanityFetch } from '@/sanity/lib/fetch'
import { ROOT_QUERYResult } from '@/sanity.types'
import { ROOT_QUERY } from '@/sanity/queries'
import NavBar from './NavBar'
import { formatColor } from '@/services/utility-functions'

export const runtime = 'edge'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app'
}

export default async function RootLayout({
  children
}: Readonly<{
  children: React.ReactNode
}>) {
  const data = await sanityFetch<ROOT_QUERYResult>({ query: ROOT_QUERY })

  console.log('root data', data)

  const style = {
    '--bg': formatColor(data?.backgroundColor!),
    '--bg2': formatColor(data?.backgroundAltColor!),
    '--fg': formatColor(data?.foregroundColor!),
    '--accent': formatColor(data?.accentColor!),
    '--accent2': formatColor(data?.accentAltColor!),
    '--body': `${data?.bodyFont?.name}`,
    '--heading': `${data?.headingFont?.name}`,
    '--topbar': '60px'
  } as React.CSSProperties

  return (
    <html lang='en' style={style}>
      <head>
        {data?.bodyFont?.linkSource && (
          <link rel='stylesheet' href={data.bodyFont!.linkSource} />
        )}
        {data?.headingFont?.linkSource && (
          <link rel='stylesheet' href={data.headingFont!.linkSource} />
        )}
      </head>
      <body className={`bg-bg font-body text-fg ${inter.className}`}>
        <NavBar />

        {children}
      </body>
    </html>
  )
}
