import { sanityFetch } from '@/sanity/lib/fetch'
import type { Metadata } from 'next'
import NavBar from './NavBar'
import './globals.css'
import { formatColor } from '@/services/utility-functions'
import { Color } from '@/sanity.types'

export const runtime = 'edge'

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app'
}

export default async function RootLayout({
  children,
  params
}: Readonly<{
  children: React.ReactNode
  params
}>) {
  const data = {
    backgroundColor: { rgb: { r: 0, g: 0, b: 0 } },
    backgroundAltColor: { rgb: { r: 19, g: 18, b: 38 } },
    foregroundColor: { rgb: { r: 255, g: 255, b: 255 } },
    accentColor: { rgb: { r: 48, g: 80, b: 82 } },
    accentAltColor: { rgb: { r: 217, g: 216, b: 167 } },
    bodyFont: { name: 'Cormorant Garamond', linkSource: '' },
    headingFont: { name: 'Dosis', linkSource: '' }
  }
  const style = {
    // @ts-ignore
    '--bg': formatColor(data?.backgroundColor),
    // @ts-ignore
    '--bg2': formatColor(data?.backgroundAltColor),
    // @ts-ignore
    '--fg': formatColor(data?.foregroundColor),
    // @ts-ignore
    '--accent': formatColor(data?.accentColor),
    // @ts-ignore
    '--accent2': formatColor(data?.accentAltColor),
    '--body': `${data?.bodyFont?.name}`,
    '--heading': `${data?.headingFont?.name}`,
    '--topbar': '60px'
  } as React.CSSProperties

  return (
    <html lang='en' style={style}>
      <head>
        {data?.bodyFont?.linkSource && (
          <link rel='stylesheet' href={data.bodyFont!.linkSource} />
        )}
        {data?.headingFont?.linkSource && (
          <link rel='stylesheet' href={data.headingFont!.linkSource} />
        )}
      </head>
      <body className={`bg-bg font-body text-fg`}>
        <NavBar title={'My Site'} />
        {children}
      </body>
    </html>
  )
}
